services:
  # Caddy service
  caddy:
    image: caddy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - sendportal
    networks:
      - shared-network

  # PostgreSQL service
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: giga
      POSTGRES_PASSWORD: giga
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - shared-network

  # Sendportal service
  sendportal:
    image: php:7.3-apache
    working_dir: /var/www/html
    volumes:
      - ./sendportal:/var/www/html
    environment:
      - DB_HOST=postgres
      - DB_DATABASE=sendportal
      - DB_USERNAME=giga
      - DB_PASSWORD=giga
    depends_on:
      - postgres
    entrypoint: |
      /bin/sh -c "\
      if [ -f /var/www/html/.sendportal.env ]; then \
        mv /var/www/html/.sendportal.env /var/www/html/.env; \
      fi && \
      composer install "
    networks:
      - shared-network

  # Postiz service
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: "https://post.gigapros.io"
      FRONTEND_URL: "https://post.gigapros.io"
      NEXT_PUBLIC_BACKEND_URL: "https://post.gigapros.io/api"
      JWT_SECRET: "76a218bb-e83b-4ca3-a8c7-8c3c7abb0271"
      DATABASE_URL: "postgresql://giga:20eee0e04edf4f32a763829d021aa061@host.docker.internal:5432/giga"
      REDIS_URL: "redis://host.docker.internal:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 3030:5000
    networks:
      - shared-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  shared-network:
    external: false

volumes:
  postgres_data:
  postiz-config:
  postiz-uploads:
