[app]
# Interface and port where the app will run its webserver.
address = "0.0.0.0:3040"

# Database.
[db]
host = "postgres"  # Connect to the shared postgres service
port = 5432
user = "giga"  # Updated to match the credentials in docker-compose
password = "giga"
database = "giga"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"