name: Deploy EC2 Instance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure AWS credentials using GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Change the region if needed

    # Describe the available NixOS AMIs
    - name: Describe NixOS AMIs
      run: |
        aws ec2 describe-images --owners 427812963091 \
          --filters 'Name=name,Values=nixos/24.05*' \
          'Name=architecture,Values=arm64'

    # (Optional) Add steps here to launch the EC2 instance using the AMI ID
    # - name: Launch EC2 Instance
    #   run: |
    #     aws ec2 run-instances --image-id <ami-id> \
    #       --instance-type t4g.micro \
    #       --key-name <your-key-pair> \
    #       --security-group-ids <your-security-group-id> \
    #       --subnet-id <your-subnet-id> \
    #       --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyNixOSInstance}]'
