name: Deploy EC2 Instance

# Trigger the workflow manually and on push to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      # Step 3: Describe the available NixOS AMIs and set AMI_ID as an environment variable
      - name: Describe NixOS AMIs
        id: describe_ami
        run: |
          AMI_ID=$(aws ec2 describe-images --owners 427812963091 \
            --filters 'Name=name,Values=nixos/24.05*' \
            'Name=architecture,Values=arm64' \
            --query 'Images[0].ImageId' --output text)
          
          if [ -z "$AMI_ID" ]; then
            echo "No AMI found matching the criteria."
            exit 1
          fi
          
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      # Step 4: Launch the EC2 instance without specifying security groups
      - name: Launch EC2 Instance
        id: launch_instance
        run: |
          echo "Launching EC2 instance with AMI ID: $AMI_ID"
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id "$AMI_ID" \
            --instance-type t4g.micro \
            --key-name "${{ secrets.EC2_KEY_NAME }}" \
            --subnet-id "${{ secrets.SUBNET_ID }}" \
            --associate-public-ip-address \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${{ secrets.EC2_TAG_NAME }}}]" \
            --query 'Instances[0].InstanceId' \
            --output text)
          
          if [ -z "$INSTANCE_ID" ]; then
            echo "Failed to launch EC2 instance."
            exit 1
          fi
          
          echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV

      # Step 5: Wait for the instance to be in running state
      - name: Wait for EC2 Instance to be Running
        run: |
          echo "Waiting for instance $INSTANCE_ID to enter 'running' state..."
          aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
          echo "Instance $INSTANCE_ID is now running."

      # Step 6: Retrieve the Network Interface ID associated with the instance
      - name: Retrieve Network Interface ID
        id: get_network_interface
        run: |
          NETWORK_INTERFACE_ID=$(aws ec2 describe-instances \
            --instance-ids "$INSTANCE_ID" \
            --query 'Reservations[0].Instances[0].NetworkInterfaces[0].NetworkInterfaceId' \
            --output text)
          
          if [ -z "$NETWORK_INTERFACE_ID" ]; then
            echo "Failed to retrieve Network Interface ID."
            exit 1
          fi
          
          echo "NETWORK_INTERFACE_ID=${NETWORK_INTERFACE_ID}" >> $GITHUB_ENV

      # Step 7: Attach the Security Group to the Network Interface
      - name: Attach Security Group to Network Interface
        run: |
          echo "Attaching Security Group ${SECURITY_GROUP_ID} to Network Interface ${NETWORK_INTERFACE_ID}"
          aws ec2 modify-network-interface-attribute \
            --network-interface-id "$NETWORK_INTERFACE_ID" \
            --groups "${{ secrets.SECURITY_GROUP_ID }}"
          
          echo "Security Group attached successfully."
